In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_dataset.csv")
df.head()

,Locality,Type of property,Subtype of property,Price,Number of rooms,Living Area,Terrace Area,Garden Area,Surface of the land,Number of facades,State of the building,Furnished,Terrace,Garden,Swimming pool
0,Hastière-Lavaux,house,bungalow,19000.0,1.0,49.0,15.0,200.0,242.0,NaN,To be renovated,0,1,1,0
1,Klerken,house,villa,NaN,3.0,203.0,NaN,NaN,634.0,4.0,Excellent,0,1,1,0
2,Rumbeke,house,bungalow,1.0,3.0,126.0,12.0,438.0,580.0,4.0,To be renovated,0,1,1,0
3,Arlon,house,mansion,NaN,2.0,209.0,NaN,NaN,34508.0,4.0,Excellent,0,1,1,0
4,Mazée,house,residence,1100.0,3.0,255.0,NaN,169.0,374.0,3.0,NaN,0,0,1,0

In [5]:
df.describe()

,Price,Number of rooms,Living Area,Terrace Area,Garden Area,Surface of the land,Number of facades,Furnished,Terrace,Garden,Swimming pool
count,2.675500e+04,26727.000000,25495.000000,10855.000000,6192.000000,13937.000000,20963.000000,27268.000000,27268.000000,27268.000000,27268.000000
mean,3.934163e+05,3.038725,166.168464,25.961032,1041.030039,1205.268422,2.800267,0.026881,0.724696,0.576170,0.030805
std,4.121083e+05,12.132477,163.690847,49.637123,9997.724419,4251.892103,0.837325,0.161740,0.446676,0.494173,0.172793
min,1.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.240000e+05,2.000000,94.000000,10.000000,85.000000,222.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,3.200000e+05,3.000000,136.000000,17.000000,232.500000,465.000000,3.000000,0.000000,1.000000,1.000000,0.000000
75%,4.490000e+05,4.000000,191.000000,30.000000,642.000000,987.000000,4.000000,0.000000,1.000000,1.000000,0.000000
max,2.600000e+07,1962.000000,13289.000000,2968.000000,690330.000000,178367.000000,4.000000,1.000000,1.000000,1.000000,1.000000